--- #YAML:1.0
name:                OpenCA-OpenSSL
version:             2.0.29
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    X500::DN:                      0.27
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
